apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bank-user-cleanup-utility
  labels:
    app: bank-user-cleanup-utility
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "true"
        spec:
          restartPolicy: OnFailure
          containers:
          - name: bank-user-cleanup-utility
            image: ykoyfman/bank-user-cleanup-utility:mesh
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: bank-db-secret
            - secretRef:
                name: bank-iam-secret
            - secretRef:
                name: bank-appid-secret
            env:
            - name: LAST_LOGIN_HOURS
              value: "24"
      backoffLimit: 0
